# docker build -f dockerfile_igver -t shahcompbio/igver .
# docker push shahcompbio/igver

# setup: using archlinux because it was the only distro where I could find --auto-display
FROM archlinux:latest

RUN pacman -Syu --noconfirm  xorg-server-xvfb python wget pacman jre11-openjdk unzip git libxtst

# get IGV
RUN wget https://data.broadinstitute.org/igv/projects/downloads/2.14/IGV_2.14.1.zip && \
    unzip IGV_2.14.1.zip -d /opt && \
	rm IGV_2.14.1.zip
RUN mkdir -p /opt/IGV_2.14.1/genomes 

WORKDIR /opt/IGV_2.14.1

# font config
RUN pacman -Syu --noconfirm  gnu-free-fonts opendesktop-fonts ttf-dejavu fontconfig
RUN fc-cache -f -v

# download igver
RUN git clone https://github.com/shahcompbio/igver.git /opt/igver
ENV PATH="$PATH:/opt/igver:/opt/IGV_2.14.1"

# add genomes (from https://github.com/igvteam/igv/wiki/Downloading-Hosted-Genomes-for-Offline-Use#hosted-genome-list)
ADD json/ASM294v2.json /opt/IGV_2.14.1/genomes/ASM294v2.json
ADD json/ASM985889v3.json /opt/IGV_2.14.1/genomes/ASM985889v3.json
ADD json/bosTau8.json /opt/IGV_2.14.1/genomes/bosTau8.json
ADD json/bosTau9.json /opt/IGV_2.14.1/genomes/bosTau9.json
ADD json/canFam3.json /opt/IGV_2.14.1/genomes/canFam3.json
ADD json/canFam5.json /opt/IGV_2.14.1/genomes/canFam5.json
ADD json/ce11.json /opt/IGV_2.14.1/genomes/ce11.json
ADD json/danRer10.json /opt/IGV_2.14.1/genomes/danRer10.json
ADD json/danRer11.json /opt/IGV_2.14.1/genomes/danRer11.json
ADD json/dm3.json /opt/IGV_2.14.1/genomes/dm3.json
ADD json/dm6.json /opt/IGV_2.14.1/genomes/dm6.json
ADD json/dmel_r5.9.json /opt/IGV_2.14.1/genomes/dmel_r5.9.json
ADD json/galGal6.json /opt/IGV_2.14.1/genomes/galGal6.json
ADD json/gorGor4.json /opt/IGV_2.14.1/genomes/gorGor4.json
ADD json/gorGor6.json /opt/IGV_2.14.1/genomes/gorGor6.json
ADD json/hg18.json /opt/IGV_2.14.1/genomes/hg18.json
ADD json/hg19.json /opt/IGV_2.14.1/genomes/hg19.json
ADD json/hg38.json /opt/IGV_2.14.1/genomes/hg38.json
ADD json/hg38_1kg.json /opt/IGV_2.14.1/genomes/hg38_1kg.json
ADD json/macFas5.json /opt/IGV_2.14.1/genomes/macFas5.json
ADD json/mm10.json /opt/IGV_2.14.1/genomes/mm10.json
ADD json/mm9.json /opt/IGV_2.14.1/genomes/mm9.json
ADD json/panPan2.json /opt/IGV_2.14.1/genomes/panPan2.json
ADD json/panTro4.json /opt/IGV_2.14.1/genomes/panTro4.json
ADD json/rn6.json /opt/IGV_2.14.1/genomes/rn6.json
ADD json/sacCer3.json /opt/IGV_2.14.1/genomes/sacCer3.json
ADD json/tair10.json /opt/IGV_2.14.1/genomes/tair10.json

# custom genome (hs1 from https://s3.amazonaws.com/igv.org.genomes/genomes.json)
ADD json/hs1.json /opt/IGV_2.14.1/genomes/hs1.json
