# docker build -f dockerfile_igv -t shahcompbio/igv .
# docker push shahcompbio/igv

FROM alpine:3.14

# update apk and install jdk11
RUN  apk update \
    && apk upgrade \
    && apk add ca-certificates \
    && update-ca-certificates \
    && apk add --update coreutils && rm -rf /var/cache/apk/* \
    && apk add --update openjdk11 tzdata curl unzip bash \
    && apk add --no-cache nss \
    && rm -rf /var/cache/apk/*

# install IGV 
RUN apk add wget xvfb xvfb-run
RUN wget https://data.broadinstitute.org/igv/projects/downloads/2.14/IGV_Linux_2.14.1_WithJava.zip \
    && unzip IGV_Linux_2.14.1_WithJava.zip
RUN rm -r /IGV_Linux_2.14.1_WithJava.zip

# install python 
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
