# docker build -f dockerfile_igv -t shahcompbio/igv .
# docker push shahcompbio/igv

FROM alpine:3.14

# update apk and install jdk11
RUN  apk update \
    && apk upgrade \
    && apk add ca-certificates \
    && update-ca-certificates \
    && apk add --update coreutils && rm -rf /var/cache/apk/* \
    && apk add --update openjdk11 tzdata curl unzip bash \
    && apk add --no-cache nss \
    && rm -rf /var/cache/apk/*

# install python 
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

# install IGV and related data
RUN apk add wget xvfb xvfb-run
RUN wget https://data.broadinstitute.org/igv/projects/downloads/2.14/IGV_2.14.1.zip && \
    unzip IGV_2.14.1.zip -d /opt && \
	rm IGV_2.14.1.zip
RUN mkdir -p /opt/IGV_2.14.1/genomes 

ADD hg19.fa /opt/IGV_2.14.1/genomes/hg19.fa
ADD hg19.fa.fai /opt/IGV_2.14.1/genomes/hg19.fa.fai
ADD hg19.dict /opt/IGV_2.14.1/genomes/hg19.dict
ADD cytoBand.txt /opt/IGV_2.14.1/genomes/cytoBand.txt

# set workdir
WORKDIR /opt/IGV_2.14.1

# download igver
RUN apk add git && \
    git clone https://github.com/shahcompbio/igver.git /opt/igver
ENV PATH="$PATH:/opt/igver:/opt/IGV_2.14.1"

# download fonts
RUN apk add --no-cache msttcorefonts-installer fontconfig
RUN update-ms-fonts
