# docker build -f dockerfile_igv -t shahcompbio/igv .
# docker push shahcompbio/igv

FROM alpine:3.14

# update apk and install jdk11
RUN  apk update \
    && apk upgrade \
    && apk add ca-certificates \
    && update-ca-certificates \
    && apk add --update coreutils && rm -rf /var/cache/apk/* \
    && apk add --update openjdk11 tzdata curl unzip bash \
    && apk add --no-cache nss \
    && rm -rf /var/cache/apk/*

# install python 
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

# install IGV and related data
RUN apk add wget xvfb xvfb-run
RUN wget https://data.broadinstitute.org/igv/projects/downloads/2.14/IGV_2.14.1.zip && \
    unzip IGV_2.14.1.zip -d /opt && \
	rm IGV_2.14.1.zip
RUN apt-get install -y default-jre
RUN wget https://igv.genepattern.org/genomes/seq/hg19/hg19.fasta -O hg19.fa && \
	wget https://igv.genepattern.org/genomes/seq/hg19/hg19.fasta.fai -O hg19.fa.fai && \
	wget https://igv.genepattern.org/genomes/seq/hg19/cytoBand.txt && \
	wget https://github.com/broadinstitute/picard/releases/download/3.0.0/picard.jar && \
	java -jar picard.jar CreateSequenceDictionary R=hg19.fa O=hg19.dict && \
	mkdir -p /opt/IGV_2.14.1/genomes && \
	mv hg19.* cytoBand* /opt/IGV_2.14.1/genomes/

#ADD /path/to/hg19.fa /opt/IGV_2.14.1/genomes/hg19.fa
#ADD /path/to/hg19.fa.fai /opt/IGV_2.14.1/genomes/hg19.fa.fai
#ADD /path/to/hg19.dict /opt/IGV_2.14.1/genomes/hg19.dict


